---
title: "Browse Salesforce Data"
author: "Michael Jensen"
date: "June 2019"
output: html_notebook
---
# Program Description

**Purpose**

Browse Salesforce data.

**Input(s)**

```{r}
dsn_sf  <- "Salesforce"
```

**Output(s)**



# Libraries and Data Sources

```{r}
library(magrittr)
library(odbc)
library(tidyverse)

odbc_sf  <- dbConnect(odbc::odbc(), dsn_sf)
rm(dsn_sf)
```

# Function Definitions

## Argument Definitions

```{r}

```


# Execution

## Account Table

```{r}
entity_names <- 
  dbGetQuery(
    odbc_sf,
    "SELECT
      id   AS entity_id,
      Name AS entity_name
    FROM Account")
```

```{r}
lg_names <- 
  dbGetQuery(
    odbc_sf,
    "SELECT 
      a.Name          AS entity_name,
      r.DeveloperName AS govt_type
    FROM Account AS a
    LEFT JOIN RecordType AS r
    ON a.RecordTypeID = r.Id
    Where RecordTypeID IN (
      SELECT Id
      FROM RecordType
      WHERE DeveloperName IN (
        'AOG',
        'City',
        'Community_Reinvestment_Agency',
        'Conservation_District',
        'County',
        'District_Health',
        'Educational_Foundation',
        'Financial_Institution',
        'Housing',
        'Independent_Quasi_State_Entity',
        'Institute_of_Higher_Education',
        'Interlocal',
        'Local_and_Special_Service_District',
        'Mental_Health',
        'Non_Profits',
        'Redevelopment_Agency_Project_Area',
        'School_District_or_Charter_School',
        'State_Agency',
        'Town',
        'Justice_Court'))
    AND a.Name <> 'test city 2'")
```

## RecordType Table

```{r}
record_type <- 
  dbGetQuery(
    odbc_sf,
    "SELECT DISTINCT DeveloperName
    FROM RecordType")
```

## RecordType Table

```{r}
record_type <- 
  dbGetQuery(
    odbc_sf,
    "SELECT DISTINCT Name
    FROM RecordType") %>% 
  arrange()
```

## Report_Review__c Table

```{r}
report_review__c_2018 <- 
  dbGetQuery(
    odbc_sf,
    "SELECT 
      a.Name                            AS entity_name,
      y.Name                            AS report_year,
      t.Name                            AS record_type,
      r.Total_Revenue_or_Expenditure__c AS total_rev_or_exp,
      r.Total_Expenditure__c            AS total_exp,
      r.Total_Revenue__c                AS total_rev
    FROM Report_Review__c               AS r
    LEFT JOIN Account                   AS a
    ON r.Entity_Name__c = a.Id
    LEFT JOIN RecordType                AS t
    ON r.RecordTypeID = t.Id
    LEFT JOIN Report_Year__c            AS y
    ON r.review_report_year__c = y.Id
    WHERE t.Name IN (
      'AUP Checklist',
      'Large Entity Checklist',
      'LEA Checklist',
      'Small Entity Checklist')
    AND r.review_report_year__c IN (
      SELECT Id
      FROM Report_Year__c
      WHERE Name = '2018')") %>% 
  mutate(total = 
           if_else(
             !is.na(total_rev_or_exp), 
             total_rev_or_exp,
             if_else(
               total_exp > total_rev,
               total_exp,
               total_rev)))
```

## Transparency_Reporting_c Table

```{r}
transparency_reporting__c <- 
  dbGetQuery(
    odbc_sf,
    "SELECT 
      IsDeleted        AS is_deleted,
      Name             AS report_date_name,
      CreatedDate      AS created_date,
      CreatedById      AS created_by,
      LastModifiedDate AS last_modified_date,
      LastModifiedById AS last_modified_by,
      Account__c       AS entity_id,
      Status__c        AS transparency_status,
      Id               AS id
    FROM Transparency_Reporting__c") %>% 
  left_join(entity_names, by = "entity_id") %>% 
  left_join(user_names,   by = c("created_by" = "user_id")) %>% 
  left_join(user_names,   by = c("created_by" = "user_id")) %>% 
  rename(created_by_name       = user_name.x,
         last_modified_by_name = user_name.y) %>% 
  select(report_date_name, entity_name, transparency_status, created_date,
         created_by_name, last_modified_date, last_modified_by_name, is_deleted,
         entity_id, created_by, last_modified_by, id)
```

## Transparency_Reporting__c_hd Table

```{r}
transparency_reporting__c_hd <- 
  dbGetQuery(
    odbc_sf,
    "SELECT 
      ParentId AS parent_id,
      IsDeleted AS is_deleted,
      ValidFromDate AS valid_from_date,
      CreatedDate AS created_date,
      CreatedById AS created_by,
      Status__c_hpr,
      Status__c_hst
    FROM Transparency_Reporting__c_hd") %>% 
  left_join(user_names, by = c("created_by" = "user_id"))
```

## User Names

```{r}
user_names <- 
  dbGetQuery(
    odbc_sf,
    "SELECT
      Id   AS user_id,
      Name AS user_name
    FROM User")
```

# Workspace

# DBMS Disconnection

```{r}
dbDisconnect(odbc_sf)
```